import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const currentDir = dirname(fileURLToPath(import.meta.url))
const drawer = readFileSync(join(currentDir, 'AiAudienceDrawer.vue'), 'utf8')
const normalMode = readFileSync(join(currentDir, 'NormalMode.vue'), 'utf8')
const app = readFileSync(join(currentDir, '..', 'App.vue'), 'utf8')
const taskCenter = readFileSync(join(currentDir, 'TaskCenter.vue'), 'utf8')
const floatingLauncher = readFileSync(join(currentDir, 'AiFloatingLauncher.vue'), 'utf8')
const feedback = readFileSync(join(currentDir, 'FeedbackDrawer.vue'), 'utf8')
const categoryPreferences = readFileSync(join(currentDir, '..', 'utils', 'aiCategoryPreferences.js'), 'utf8')

test('AI audience builder is a movable global entry', () => {
  assert.match(app, /<AiFloatingLauncher/)
  assert.match(app, /<AiAudienceDrawer/)
  assert.match(app, /event\.key\.toLowerCase\(\) !== 'k'/)
  assert.match(floatingLauncher, /@pointerdown="startDrag"/)
  assert.match(floatingLauncher, /AI 圈人/)
  assert.doesNotMatch(normalMode, /class="ai-library-launcher"/)
})

test('drawer checks model status and sends conversational context', () => {
  assert.match(drawer, /request\('\/api\/ai\/status'\)/)
  assert.match(drawer, /request\('\/api\/ai\/chat'/)
  assert.match(drawer, /currentIntent: currentIntent\.value/)
  assert.match(drawer, /pendingQuestions: plan\.value\?\.questions \|\| \[\]/)
  assert.match(drawer, /questionAnswer:/)
  assert.match(drawer, /currentWorkflow: currentWorkflow\.value/)
  assert.match(drawer, /currentOperation: currentOperation\.value/)
  assert.match(drawer, /模型在线/)
  assert.match(drawer, /等待管理员配置大模型/)
})

test('confirmed DMP operations call the real task center workflow and open comparison', () => {
  assert.match(drawer, /emit\('execute'/)
  assert.match(drawer, /使用默认标签并开始取数/)
  assert.match(drawer, /删除月均消费金额/)
  assert.match(drawer, /新增人生阶段/)
  assert.match(drawer, /把用户年龄移到第1个/)
  assert.match(drawer, /默认就行/)
  assert.match(app, /action !== 'prepare_dmp_batch_profile'/)
  assert.match(app, /appMode\.value = 'task-center'/)
  assert.match(taskCenter, /await runDmp\(\)/)
  assert.match(taskCenter, /monitorView\.value = 'comparison'/)
  assert.match(taskCenter, /resolveAiTagIds\(command\.tagIds, command\.tagNames\)/)
  assert.match(taskCenter, /dictionaryById\.has\(tagId\)/)
  assert.doesNotMatch(taskCenter, /DMP_AI_TAG_ALIASES/)
})

test('AI operation card follows the real task execution result', () => {
  assert.match(app, /:execution-state="aiTaskExecutionState"/)
  assert.match(app, /@ai-execution-status="handleAiExecutionStatus"/)
  assert.match(app, /status: 'queued'/)
  assert.match(app, /\['completed', 'partial', 'failed', 'cancelled'\]\.includes/)
  assert.match(app, /aiTaskCommand\.value = null/)
  assert.match(taskCenter, /defineEmits\(\['ai-execution-status'\]\)/)
  assert.match(taskCenter, /reportAiExecution\(command, 'running'/)
  assert.match(taskCenter, /reportAiExecution\(command, status, message/)
  assert.match(drawer, /operationStatusLabel/)
  assert.match(drawer, /completed: '已完成'/)
  assert.match(drawer, /partial: '部分完成'/)
  assert.match(drawer, /failed: '执行失败'/)
  assert.match(drawer, /messages\.value\.push\(/)
  assert.doesNotMatch(drawer, /currentOperation\.status === 'ready' \? '执行中' : '待确认'/)
})

test('conversation can be exported as a safe debugging snapshot', () => {
  assert.match(drawer, /导出对话/)
  assert.match(drawer, /function buildConversationDebugExport/)
  assert.match(drawer, /schemaVersion: 1/)
  assert.match(drawer, /conversation: messages\.value\.map\(exportableConversationMessage\)/)
  assert.match(drawer, /currentIntent: currentIntent\.value/)
  assert.match(drawer, /currentOperation: currentOperation\.value/)
  assert.match(drawer, /executionState: props\.executionState/)
  assert.match(drawer, /DEBUG_EXPORT_SENSITIVE_KEY/)
  assert.match(drawer, /URL\.createObjectURL\(blob\)/)
  assert.match(drawer, /X-Data_AI对话_/)
})

test('AI progress and typewriter feedback remain visible during generation', () => {
  assert.match(drawer, /thinkingStages = \[/)
  assert.match(drawer, /正在推演圈包路径/)
  assert.match(drawer, /beginThinkingProcess\(\)/)
  assert.match(drawer, /typeAssistantReply\(/)
  assert.match(drawer, /item\.displayContent \?\? item\.content/)
  assert.match(drawer, /ai-type-cursor/)
})

test('incomplete AI requests use one compact guidance card before the full plan', () => {
  assert.match(drawer, /v-if="showGuidanceCard" class="ai-guidance"/)
  assert.match(drawer, /CURRENT UNDERSTANDING/)
  assert.match(drawer, /understoodItems/)
  assert.match(drawer, /activeGuidancePrompt/)
  assert.match(drawer, /guidanceQuickAnswers/)
  assert.match(drawer, /isGuidanceEcho\(item\)/)
  assert.match(drawer, /v-if="plan\?\.status === 'ready'" class="ai-plan is-ready"/)
  assert.match(drawer, /\['浏览', '购买', '收藏', '加购', '预售', '退款', '评论'\]/)
  assert.match(drawer, /近30天 对比 前30天/)
  assert.match(drawer, /今年 YTD/)
  assert.match(drawer, /核心范围/)
})

test('preview labels and live option lists stay human readable', () => {
  assert.match(drawer, /function componentLabel\(value\)/)
  assert.match(drawer, /raw\.map\(componentLabel\)\.filter\(Boolean\)/)
  assert.match(drawer, /分析类目 · 可搜索单选/)
  assert.match(drawer, /品牌核心类目 · 可搜索多选/)
  assert.match(drawer, /确认全部类目/)
  assert.match(drawer, /核心类目总数不限；超过10项会在最后确认时自动拆成多个组件/)
  assert.match(drawer, /默认选全店销售额前10项；自定义可多选/)
  assert.match(drawer, /function limitCategorySelections\(question, values = \[\]\)/)
  assert.match(drawer, /max-collapse-tags="3"/)
  assert.match(drawer, /按业务类目筛选/)
  assert.match(categoryPreferences, /美妆护肤/)
  assert.match(categoryPreferences, /母婴护理/)
  assert.match(categoryPreferences, /个护清洁/)
  assert.match(drawer, /选择保存到你的账号/)
  assert.match(drawer, /rememberAiCategoryOption/)
  assert.match(drawer, /request\('\/api\/ai\/category-preferences'/)
  assert.match(drawer, /换电脑登录也会保留/)
  assert.match(drawer, /mode: 'merge'/)
  assert.match(drawer, /mode: 'upsert'/)
  assert.match(drawer, /本次系统路径/)
  assert.match(drawer, /workflowStageLabel/)
  assert.match(drawer, /确认并准备基础方案/)
  assert.match(drawer, /function sortedQuestionOptions\(question\)/)
  assert.match(drawer, /is-formal-brand/)
  assert.match(drawer, /node\.displayName \|\| node\.packageType/)
})

test('plan remains preview-only until the user explicitly applies it', () => {
  assert.match(drawer, /plan\?\.status === 'ready'/)
  assert.match(drawer, /确认并应用到工作台/)
  assert.match(drawer, /emit\('apply', \{/)
  assert.match(normalMode, /await confirmReplaceCanvas\(/)
  assert.match(normalMode, /const hydratedNodes = await hydrateNodes\(nodes\)/)
  assert.match(normalMode, /nodeList\.value = hydratedNodes/)
})

test('relative date previews explicitly exclude today', () => {
  assert.match(drawer, /最近 \$\{value\.days\} 天（截至昨天）/)
})

test('account permission questions and feedback action are actionable', () => {
  assert.match(drawer, /question\.answerType === 'boolean'/)
  assert.match(drawer, /可以使用/)
  assert.match(drawer, /不能使用/)
  assert.match(drawer, /\$emit\('request-feedback', action\)/)
  assert.match(app, /function handleAiFeedback/)
  assert.match(app, /window\.addEventListener\('cdp:open-feedback', handleOpenFeedback\)/)
  assert.match(feedback, /value\.message\.slice\(0, 2000\)/)
})
