export const CATEGORY_ITEM_TUTORIAL_ID = 'category-item-behavior-split'
export const DMP_BATCH_TUTORIAL_ID = 'dmp-batch-profile-comparison'
export const SOLUTION_REUSE_TUTORIAL_ID = 'competitor-overlap-solution-reuse'
export const PULL_ANALYSIS_GROUP_TUTORIAL_ID = 'pull-analysis-solution-group'
export const PARAMETER_BATCH_TUTORIAL_ID = 'competitor-brand-parameter-batch'
export const COMBINATION_BATCH_TUTORIAL_ID = 'combination-competitor-batch'
export const COMBINATION_BATCH_BRANDS = Object.freeze(['Lancome/兰蔻', 'Estee Lauder/雅诗兰黛', 'HR/赫莲娜'])

export const CATEGORY_ITEM_TUTORIAL_VALUES = Object.freeze({
  audienceName: '近30天购买指定7商品人群',
})

export const SOLUTION_REUSE_TUTORIAL_VALUES = Object.freeze({
  packageType: '类目公域行为',
  behavior: '浏览',
  initialCategory: '美容护肤/美体/精油>化妆水/爽肤水',
  secondCategory: '美容护肤/美体/精油>面部护理套装',
  ownBrand: 'SK-II',
  initialCompetitorBrand: 'Shiseido/资生堂',
  secondCompetitorBrand: 'CPB/肌肤之钥',
  channel: '天猫',
  recentDays: 30,
  solutionName: '拉力分析｜共同浏览本品与竞品',
  defaultCrowdName: '共同浏览｜SK-II × 资生堂｜化妆水/爽肤水',
  secondCrowdName: '共同浏览｜SK-II × CPB｜面部护理套装',
})

export const PULL_ANALYSIS_GROUP_TUTORIAL_VALUES = Object.freeze({
  baseSolutionName: SOLUTION_REUSE_TUTORIAL_VALUES.solutionName,
  ownPurchaseSolutionName: '拉力分析｜共同浏览且购买本品',
  ownPurchaseCrowdName: '共同浏览且购买本品｜SK-II × 资生堂｜化妆水/爽肤水',
  competitorPurchaseSolutionName: '拉力分析｜共同浏览且购买竞品',
  competitorPurchaseCrowdName: '共同浏览且购买竞品｜SK-II × 资生堂｜化妆水/爽肤水',
  folderName: '拉力分析｜本品与竞品浏览转化',
  batchCategory: SOLUTION_REUSE_TUTORIAL_VALUES.secondCategory,
  batchCompetitorBrand: SOLUTION_REUSE_TUTORIAL_VALUES.secondCompetitorBrand,
  baselineCrowdNames: Object.freeze([
    SOLUTION_REUSE_TUTORIAL_VALUES.defaultCrowdName,
    '共同浏览且购买本品｜SK-II × 资生堂｜化妆水/爽肤水',
    '共同浏览且购买竞品｜SK-II × 资生堂｜化妆水/爽肤水',
  ]),
  finalCrowdNames: Object.freeze([
    '共同浏览｜SK-II × CPB｜面部护理套装',
    '共同浏览且购买本品｜SK-II × CPB｜面部护理套装',
    '共同浏览且购买竞品｜SK-II × CPB｜面部护理套装',
  ]),
})

export const PARAMETER_BATCH_TUTORIAL_VALUES = Object.freeze({
  packageType: '类目公域行为',
  behavior: '购买',
  category: '美容护肤/美体/精油>化妆水/爽肤水',
  initialBrand: 'CPB/肌肤之钥',
  channel: '天猫',
  recentDays: 30,
  customFieldName: '竞争品牌',
  solutionName: '竞品购买人群｜化妆水/爽肤水',
  defaultCrowdName: '近30天购买｜化妆水/爽肤水',
  brands: Object.freeze([
    'CPB/肌肤之钥',
    'Lancome/兰蔻',
    'Estee Lauder/雅诗兰黛',
    'HR/赫莲娜',
  ]),
})

export const CATEGORY_ITEM_TUTORIAL_PRODUCT_IDS = Object.freeze([
  '566446518116',
  '620909794925',
  '537574170700',
  '540211731451',
  '634025846178',
  '577875075059',
  '1055622646901',
])

export const CATEGORY_ITEM_TUTORIAL_STEPS = Object.freeze([
  {
    id: 'clean-workbench',
    target: '[data-tutorial-target="clean-workbench"]',
    eyebrow: '开始前准备',
    title: '圈包画布已经为你自动清空',
    body: '教程会自动移除原有节点和参数，从一张干净画布开始。当前高亮的整个中间栏，就是接下来实际搭建人群条件的区域。',
    hint: '确认画布已经为空，然后开始搭建。',
  },
  {
    id: 'add-category-item',
    target: '[data-tutorial-target="add-category-item"]',
    eyebrow: '搭建组件',
    title: '添加「类目商品行为」',
    body: '在左侧行为组件库中点击“添加 类目商品行为”。它适合用商品 ID 圈选某一类具体商品行为。',
    hint: '现在只需要添加这一个组件。',
  },
  {
    id: 'select-behavior',
    target: '[data-tutorial-target="select-behavior"]',
    eyebrow: '设置通用参数',
    title: '任选一个业务行为',
    body: '加购、收藏、浏览、评论、购买或预售都可以选择。本教程推荐“购买”，但你可以根据自己的业务目标任选；所选行为会复制到后续拆出的每个节点。',
    hint: '推荐选择“购买”；选择任意一个行为即可继续。',
  },
  {
    id: 'set-time',
    target: '[data-tutorial-target="set-time"]',
    eyebrow: '设置通用参数',
    title: '选择适合业务的时间范围',
    body: '“过去 N 天”或“固定日期”都可以。本教程推荐近 30 天；拆分时系统会把你选择的时间自动复制到 7 个节点，无需逐个重复填写。',
    hint: '推荐“过去 30 天”；确认任意有效时间后即可继续。',
  },
  {
    id: 'copy-ids',
    target: null,
    eyebrow: '准备批量数据',
    title: '一次复制 7 个商品 ID',
    body: '真实工作中可以直接从 Excel 复制一整列。这里先用教程提供的 7 个 ID，点击下方按钮一次复制。',
    hint: '系统支持换行、逗号和 Tab 分隔。',
  },
  {
    id: 'paste-ids',
    target: '[data-tutorial-target="paste-product-ids"]',
    eyebrow: '批量输入',
    title: '粘贴到「商品 ID」',
    body: '实际工作中，你可以直接从 Excel 复制一整列商品 ID 粘贴过来。为了先熟悉流程，本次教程以示例中的 7 个商品 ID 为主；系统会先解析内容并展示匹配结果，不会立即拆分。',
    hint: '优先粘贴示例中的 7 个商品 ID；自己的 Excel 一列也可以直接替换。',
  },
  {
    id: 'add-product-ids',
    target: '[data-tutorial-target="add-product-ids"]',
    focusPadding: 0,
    focusRadius: 7,
    eyebrow: '检查解析结果',
    title: '确认添加 7 项',
    body: '确认解析结果为 7 项后，点击“添加 7 项”。因为单个类目商品行为组件只能放 1 个商品 ID，系统接下来会询问是否自动拆分。',
    hint: '这一刻仍然可以取消，不会直接改变节点结构。',
  },
  {
    id: 'confirm-split',
    target: '.el-message-box__btns .el-button--primary',
    eyebrow: '自动拆分',
    title: '确认拆分为 7 个并集节点',
    body: '系统已经识别到商品 ID 超限。点击“确认拆分”，7 个 ID 会各自进入一个节点，之前填写的行为和时间会被完整复制。',
    hint: '节点之间使用“并”，表示命中任意一个商品即可。',
  },
  {
    id: 'inspect-split',
    target: '[data-tutorial-target="split-result"]',
    eyebrow: '核对结果',
    title: '检查系统生成的 7 个节点',
    body: '滚动查看画布：每个节点应有 1 个商品 ID，并保留你刚才选择的行为和时间；第 2—7 个节点与前一个节点的关系应为“并”。',
    hint: '看懂结果后，点击“结果正确”。',
  },
  {
    id: 'name-audience',
    target: '[data-tutorial-target="audience-name"]',
    eyebrow: '完成建包信息',
    title: '填写人群包名称',
    body: `给本次圈选结果起一个便于业务识别的名称，例如“${CATEGORY_ITEM_TUTORIAL_VALUES.audienceName}”。`,
    hint: '名称填写完整后，再点击“名称已填好”。',
  },
  {
    id: 'start-automation',
    target: '[data-tutorial-target="start-automation"]',
    eyebrow: '准备执行',
    title: '点击「自动化圈人」',
    body: '到这里，节点、参数和人群包名称都已准备完成。点击“自动化圈人”进入最终确认；系统不会在这一步直接执行。',
    hint: '最终执行权仍然交给用户。',
  },
  {
    id: 'final-confirm',
    target: null,
    eyebrow: '最终确认',
    title: '确认后开始自动化圈人',
    body: '请最后核对：7 个类目商品行为节点、你选择的行为和时间、节点关系为并。确认无误后再执行。',
    warning: {
      title: '请确保已登录数据引擎',
      body: '未登录会导致自动化圈人失败。如果尚未登录，请先打开数据引擎完成登录，再回来确认执行。',
    },
    hint: '执行后，教程会等待真实成功结果。',
  },
  {
    id: 'automation-running',
    target: '[data-tutorial-target="start-automation"]',
    eyebrow: '正在执行',
    title: '正在等待自动化结果',
    body: '系统正在把本次圈选任务交给数据引擎。请保持当前页面打开，成功后教程会自动进入完成页。',
    hint: '如果执行失败，可检查自动化插件后在这里重试。',
  },
  {
    id: 'tutorial-complete',
    target: null,
    eyebrow: '任务完成',
    title: '你已经独立完成了一次批量圈人',
    body: '这次你完成了：配置公共参数、批量粘贴 7 个商品 ID、自动拆成并集节点并发起圈人。下次可以把同样的方法用于自己的业务数据。',
    hint: '重点拓展：关键词、类目、品牌等限量字段，也能使用同样的批量拆分方法。',
  },
])

export const DMP_BATCH_TUTORIAL_TAGS = Object.freeze([
  { tagId: '114555', name: '用户年龄' },
  { tagId: '114554', name: '用户性别' },
  { tagId: '213510', name: '城市等级' },
  { tagId: '266238', name: '大快消策略人群（新）' },
])

export const DMP_BATCH_TUTORIAL_STEPS = Object.freeze([
  {
    id: 'open-task-center',
    target: '[data-tutorial-target="open-task-center"]',
    eyebrow: '进入达摩盘取数',
    title: '先打开「达摩盘取数」',
    body: '达摩盘批量取画像、执行进度和横向对比都在达摩盘取数中完成。点击顶部“达摩盘取数”，教程会继续带你操作真实页面。',
    hint: '现在只需点击高亮的“达摩盘取数”。',
  },
  {
    id: 'select-dmp-tags',
    target: '[data-tutorial-target="dmp-feature-tags"]',
    eyebrow: '选择画像维度',
    title: '在特征大盘勾选 4 个标签',
    body: '本次用用户年龄、用户性别、城市等级和大快消策略人群（新）演示。教程会逐个高亮这 4 个标签，选中当前标签后自动引导下一项；不限制你额外选择其他标签。',
    hint: '标签可能分布在不同分类中；四项全部勾选后自动进入下一步。',
  },
  {
    id: 'open-dmp-batch',
    target: '[data-tutorial-target="dmp-batch-trigger"]',
    eyebrow: '批量取画像',
    title: '点击达摩盘下方的「批量」',
    body: '批量模式会按名单顺序逐个采集画像，适合一次处理多个人群包。',
    hint: '点击“批量”打开人群包名单输入框。',
  },
  {
    id: 'input-dmp-crowds',
    target: '[data-tutorial-target="dmp-batch-input"]',
    eyebrow: '准备人群包名单',
    title: '输入至少 2 个人群包名称',
    body: '可以逐个输入，每完成一个名称按回车换到下一行；也可以直接从 Excel 复制一整列人群包名称粘贴过来。',
    hint: '教程至少需要 2 个名称，系统会自动去重并显示识别数量。',
  },
  {
    id: 'confirm-dmp-batch',
    target: '[data-tutorial-target="dmp-batch-run"]',
    focusPadding: 0,
    focusRadius: 8,
    eyebrow: '确认批量名单',
    title: '点击「运行 X 个」',
    body: '这里的 X 应与刚刚输入的人群包数量一致。点击后教程会先做最后的登录提醒，不会跳过确认直接执行。',
    hint: '核对识别数量后，点击高亮的运行按钮。',
  },
  {
    id: 'confirm-dmp-login',
    target: null,
    eyebrow: '执行前确认',
    title: '准备开始批量取画像',
    body: '系统将按输入顺序逐个打开达摩盘并采集所选标签的画像数据。',
    warning: {
      title: '请确保已登录达摩盘',
      body: '未登录达摩盘会导致人群包搜索或画像采集失败；同时请确认任务执行器已安装并连接。',
    },
    hint: '确认登录状态无误后，再开始真实取数。',
  },
  {
    id: 'wait-dmp-batch',
    target: '[data-tutorial-target="dmp-batch-progress"]',
    nonBlocking: true,
    eyebrow: '批量取数中',
    title: '任务会在后台逐个完成',
    body: '等待期间整张页面不会被锁住，你可以查看本次结果和任务记录。全部成功后，教程会自动引导你进入横向对比。',
    hint: '失败项会明确列出，可直接重试失败项或返回修改名单。',
  },
  {
    id: 'open-dmp-comparison',
    target: '[data-tutorial-target="dmp-horizontal-comparison"]',
    eyebrow: '进入横向对比',
    title: '点击「横向对比」',
    body: '刚刚完成的人群包已进入任务记录。接下来把它们放到同一张表里，查看不同人群在相同标签下的差异。',
    hint: '点击高亮的“横向对比”。',
  },
  {
    id: 'select-comparison-crowds',
    target: '[data-tutorial-target="dmp-comparison-packages"]',
    eyebrow: '选择对比人群',
    title: '勾选与本次取数数量相同的人群包',
    body: '在左侧任务记录末尾点击圆形选择框。刚刚批量取了几个人群包，这里就勾选几个人群包；第一个被选中的人群包会作为标签结构基准。',
    hint: '教程按数量校验；达到本次批量数量后自动继续。',
  },
  {
    id: 'select-comparison-metrics',
    target: '[data-tutorial-target="dmp-comparison-metrics"]',
    eyebrow: '选择展示字段',
    title: '选择「人群占比」和「Rebase 人群占比」',
    body: '人群占比反映某特征明细在当前人群包中的原始覆盖比例；Rebase 人群占比会在同一标签内重新归一化，用来比较该标签各明细的相对构成。',
    hint: '两个指标都选中后再继续；下方会显示准确计算口径。',
  },
  {
    id: 'inspect-comparison-table',
    target: '[data-tutorial-target="dmp-comparison-table"]',
    focusPadding: 0,
    focusRadius: 0,
    eyebrow: '查看结果',
    title: '看看刚刚选择的画像数据',
    body: '高亮区域就是刚刚选出的结果表。人群占比展示每个特征明细在当前人群包中的原始覆盖比例；Rebase 人群占比展示同一标签内重新归一化后的构成。先看一眼数据，再继续整理顺序。',
    hint: '确认表格已展示这两个指标后，点击“看懂了，继续排序”。',
  },
  {
    id: 'open-label-order',
    target: '[data-tutorial-target="dmp-label-order-trigger"]',
    eyebrow: '整理标签顺序',
    title: '打开「标签名称」排序',
    body: '点击“标签名称”左侧的拖动图标，打开整组标签排序面板。排序会同时影响表格、复制内容和 CSV 导出。',
    hint: '点击高亮图标打开排序面板。',
  },
  {
    id: 'sort-label-order',
    target: '[data-tutorial-target="dmp-label-order-zone"]',
    focusPadding: 0,
    focusRadius: 0,
    eyebrow: '整理标签顺序',
    title: '把「性别」调整到最前面',
    body: '高亮的是整个标签排序区域。拖动“性别”（部分结果显示为“用户性别”）到第一位，也可以使用右侧上移按钮；调整完成后，请点击右下角的“应用排序”保存。',
    hint: '性别排到第一位后，点击右下角“应用排序”；应用后教程才会继续。',
  },
  {
    id: 'sort-audience-order',
    target: '[data-tutorial-target="dmp-audience-order-zone"]',
    focusPadding: 3,
    focusRadius: 10,
    eyebrow: '整理人群包顺序',
    title: '把第 2 个人群包拖到第 1 位',
    body: '高亮的是整个人群包排序区域。拖动第二个人群包到最前面，表格列、复制内容和导出顺序会同步变化。',
    hint: '顺序发生一次调整后自动进入复制步骤。',
  },
  {
    id: 'copy-comparison-table',
    target: '[data-tutorial-target="dmp-copy-comparison"]',
    focusPadding: 0,
    focusRadius: 8,
    eyebrow: '带走分析结果',
    title: '直接复制横向对比表',
    body: '点击“复制表格”，系统会按当前标签顺序、人群包顺序和展示字段生成可直接粘贴到 Excel 的表格。',
    hint: '复制成功后，教程自动进入完成页。',
  },
  {
    id: 'dmp-tutorial-complete',
    target: null,
    eyebrow: '任务完成',
    title: '你已经完成一次批量取画像与横向对比',
    body: '这次你亲手完成了：选择画像标签、批量采集多个人群包、处理执行状态、选择对比指标、调整两类顺序并复制表格。',
    hint: '下次只需替换人群包名单和标签，就能复用整套流程。',
  },
])

export const SOLUTION_REUSE_TUTORIAL_STEPS = Object.freeze([
  {
    id: 'solution-clean-workbench',
    target: '[data-tutorial-target="clean-workbench"]',
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '开始前准备',
    title: '从一张干净圈包画布开始',
    body: '系统已经自动清空中间圈包画布。本章会搭建“同时浏览本品与竞品”的真实业务条件，并把它保存为可继续加工的方案草稿。',
    hint: '确认画布为空后，开始制作第一个可复用方案。',
  },
  {
    id: 'add-public-behavior',
    target: '[data-tutorial-target="add-category-public"]',
    focusPadding: 0,
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '添加组件',
    title: '添加「类目公域行为」',
    body: '这个组件可以同时限定行为、分析类目、品牌、渠道和时间，是搭建本品与竞品共同浏览条件的基础。',
    hint: '点击高亮的“添加 类目公域行为”。',
  },
  {
    id: 'set-own-behavior',
    target: '[data-tutorial-target="solution-own-bhv"]',
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '配置本品节点',
    title: '行为选择「浏览」',
    body: '第一个节点代表浏览本品的人。选择“浏览”，后续复制节点时这项参数会一起带过去。',
    hint: '必须选择“浏览”后才会继续。',
  },
  {
    id: 'set-own-category',
    target: '[data-tutorial-target="solution-own-leafCates"]',
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '配置本品节点',
    title: '设置分析类目',
    body: '搜索并选择“美容护肤/美体/精油>化妆水/爽肤水”。本次先分析化妆水与爽肤水，后面会用自定义字段一次修改两个节点的类目。',
    hint: '选中教程指定类目后自动进入下一步。',
  },
  {
    id: 'set-own-brand',
    target: '[data-tutorial-target="solution-own-stdBrand"]',
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '配置本品节点',
    title: '本品牌选择「SK-II」',
    body: '第一个节点固定代表本品牌。本教程用 SK-II 举例，之后你可以替换成自己的品牌。',
    hint: '选择 SK-II。',
  },
  {
    id: 'set-own-channel',
    target: '[data-tutorial-target="solution-own-channel"]',
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '配置本品节点',
    title: '渠道选择「天猫」',
    body: '把浏览行为限定在天猫渠道，保证本品节点和稍后复制出的竞品节点口径一致。',
    hint: '选择天猫。',
  },
  {
    id: 'set-own-time',
    target: '[data-tutorial-target="solution-own-time"]',
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '配置本品节点',
    title: '时间设置为过去 30 天',
    body: '保持“过去 N 天”，数值设为 30。这个时间会随复制动作进入竞品节点，不需要重复配置。',
    hint: '确认是过去 30 天，再继续。',
  },
  {
    id: 'duplicate-own-node',
    target: '[data-tutorial-target="duplicate-solution-node-0"]',
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '复用已配参数',
    title: '复制第一个节点',
    body: '点击节点左上方的复制图标。系统会完整复制行为、类目、品牌、渠道和时间，我们只需把新节点的品牌改成竞品。',
    hint: '注意复制后的轻量位移动画：它在说明参数被完整继承。',
  },
  {
    id: 'set-competitor-brand',
    target: '[data-tutorial-target="solution-competitor-stdBrand"]',
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '配置竞品节点',
    title: '把复制节点改为「Shiseido/资生堂」',
    body: '只修改第二个节点的标准品牌。其他参数由复制动作继承，仍保持浏览、同一分析类目、天猫和过去 30 天。',
    hint: '选择 Shiseido/资生堂。',
  },
  {
    id: 'confirm-solution-intersection',
    target: '[data-tutorial-target="solution-intersection"]',
    focusPadding: 6,
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '确认业务关系',
    title: '两个节点使用「交集」',
    body: '交集表示用户既浏览过本品，也浏览过竞品；这才是“共同浏览”。如果使用并集，只会得到浏览过任一品牌的人。',
    hint: '确认第二个节点上方显示“交集”，再继续。',
  },
  {
    id: 'save-workbench-solution',
    target: '[data-tutorial-target="save-workbench-solution"]',
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '形成方案草稿',
    title: '点击「存草稿」',
    body: '把当前两节点结构送到数据引擎取数模板。它还不是正式模板，下一章会为它制作三个业务人员可直接修改的自定义字段。',
    hint: '保存成功后，教程会记录真实草稿 ID。',
  },
  {
    id: 'open-solution-center',
    target: '[data-tutorial-target="open-solution-center"] .el-radio-button__inner',
    focusPadding: 1,
    focusRadius: 999,
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '进入数据引擎取数模板',
    title: '打开「数据引擎取数模板」',
    body: '刚刚保存的内容会以“圈包草稿”进入我的模板。接下来把底层节点参数封装成更好用的业务入口。',
    hint: '点击顶部“数据引擎取数模板”。',
  },
  {
    id: 'open-workbench-draft',
    target: '[data-tutorial-target="tutorial-workbench-draft"]',
    phase: '第 1 章 · 搭建共同浏览',
    eyebrow: '打开真实草稿',
    title: '选择刚刚保存的「圈包草稿」',
    body: '教程只认可刚才从数据引擎人群圈包生成的那一份草稿，避免误改已有正式模板。',
    hint: '点击高亮草稿，加载两个共同浏览节点。',
  },
  {
    id: 'add-analysis-field',
    target: '[data-tutorial-target="add-custom-field"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '创建分析类目',
    title: '新增第一个自定义字段',
    body: '先创建“分析类目”。它会同时控制本品节点和竞品节点的类目，是本教程最关键的一对多字段。',
    hint: '点击“新增自定义字段”。',
  },
  {
    id: 'name-analysis-field',
    target: '[data-tutorial-target="custom-field-name"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '创建分析类目',
    title: '字段名称输入「分析类目」',
    body: '名称要让使用方案的人一眼明白修改目的。输入完成后点击引导卡继续绑定。',
    hint: '必须输入“分析类目”。',
  },
  {
    id: 'bind-analysis-first',
    target: '[data-tutorial-target="solution-node-0-leafCates"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '绑定分析类目',
    title: '点击第一个节点的「类目」',
    body: '第一次点击会确定字段类型，并建立“分析类目 → 本品节点类目”的第一条绑定。请点击字段右侧或文字旁边的空白处。',
    hint: '不要点击已经选中的类目文字；点击字段空白处完成绑定。',
    warning: {
      title: '请点击字段空白处',
      body: '点击已经选中的参数会重新打开下拉框；点击同一字段内的空白位置，才能直接完成绑定。',
    },
  },
  {
    id: 'bind-analysis-second',
    target: '[data-tutorial-target="solution-node-1-leafCates"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '形成一对多绑定',
    title: '再点击第二个节点的「类目」',
    body: '现在同一个“分析类目”会控制两个节点。以后只改一次，两个节点的类目会同步变化。请点击第二个类目字段的空白处。',
    hint: '不要点击已选类目；点击字段空白处，出现第二条绑定后关系才成立。',
    warning: {
      title: '仍然点击字段空白处',
      body: '已选中的类目文字会打开下拉框，不是绑定按钮；请点击它旁边的空白位置。',
    },
  },
  {
    id: 'finish-analysis-field',
    target: '[data-tutorial-target="finish-custom-field"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '保存分析类目',
    title: '完成创建「分析类目」',
    body: '确认右侧显示 2 个绑定后，点击“完成创建”。教程会校验绑定的是两个不同节点的类目字段。',
    hint: '不是只看数量，还会检查节点和字段是否正确。',
  },
  {
    id: 'add-own-brand-field',
    target: '[data-tutorial-target="add-custom-field"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '创建本品牌',
    title: '新增「本品牌」字段',
    body: '本品牌只绑定第一个节点，让方案使用者知道哪个参数代表自己的品牌。',
    hint: '再次点击“新增自定义字段”。',
  },
  {
    id: 'name-own-brand-field',
    target: '[data-tutorial-target="custom-field-name"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '创建本品牌',
    title: '字段名称输入「本品牌」',
    body: '输入完成后，下一步只绑定第一个节点的标准品牌。',
    hint: '必须输入“本品牌”。',
  },
  {
    id: 'bind-own-brand',
    target: '[data-tutorial-target="solution-node-0-stdBrand"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '绑定本品牌',
    title: '点击第一个节点的「标准品牌」',
    body: '这条绑定把本品牌入口和 SK-II 所在节点连接起来。请点击标准品牌字段中已选品牌旁边的空白处。',
    hint: '不要点击 SK-II 标签；点击第一个节点标准品牌字段的空白处。',
    warning: {
      title: '不要点击已选品牌',
      body: '点击 SK-II 会重新打开品牌下拉框；点击字段空白处即可建立绑定。',
    },
  },
  {
    id: 'finish-own-brand-field',
    target: '[data-tutorial-target="finish-custom-field"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '保存本品牌',
    title: '完成创建「本品牌」',
    body: '教程会校验“本品牌”只绑定第一个节点的标准品牌字段。',
    hint: '确认 1 个绑定后完成创建。',
  },
  {
    id: 'add-competitor-brand-field',
    target: '[data-tutorial-target="add-custom-field"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '创建竞争品牌',
    title: '新增「竞争品牌」字段',
    body: '最后把第二个节点的标准品牌开放为竞争品牌入口。以后换竞品，不需要进入节点逐个寻找。',
    hint: '点击“新增自定义字段”。',
  },
  {
    id: 'name-competitor-brand-field',
    target: '[data-tutorial-target="custom-field-name"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '创建竞争品牌',
    title: '字段名称输入「竞争品牌」',
    body: '清晰的业务名称能降低其他同事使用方案的理解成本。',
    hint: '必须输入“竞争品牌”。',
  },
  {
    id: 'bind-competitor-brand',
    target: '[data-tutorial-target="solution-node-1-stdBrand"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '绑定竞争品牌',
    title: '点击第二个节点的「标准品牌」',
    body: '第二个节点当前是资生堂，因此它应成为“竞争品牌”的唯一绑定。请点击已选品牌旁边的字段空白处。',
    hint: '不要点击资生堂标签；点击第二个节点标准品牌字段的空白处。',
    warning: {
      title: '不要点击已选品牌',
      body: '点击资生堂会重新打开品牌下拉框；点击字段空白处即可建立绑定。',
    },
  },
  {
    id: 'finish-competitor-brand-field',
    target: '[data-tutorial-target="finish-custom-field"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '保存竞争品牌',
    title: '完成创建「竞争品牌」',
    body: '三个字段都创建完成后，底层节点将被封装成三个业务人员看得懂的参数入口。',
    hint: '点击“完成创建”。',
  },
  {
    id: 'inspect-field-map',
    target: '[data-tutorial-target="custom-field-panel"]',
    phase: '第 2 章 · 制作一对多字段',
    eyebrow: '理解方案价值',
    title: '看懂三个字段的控制关系',
    body: '分析类目同时连接两个节点；本品牌只连接第一个节点；竞争品牌只连接第二个节点。这一步决定了以后换类目或竞品时需要改多少参数。',
    hint: '确认映射关系后进入保存与发布。',
  },
  {
    id: 'set-solution-identity',
    target: '[data-tutorial-target="solution-identity"]',
    phase: '第 3 章 · 保存并提交方案',
    eyebrow: '补全方案信息',
    title: '设置方案名称和默认人群包名称',
    body: '方案名称填写“拉力分析｜共同浏览本品与竞品”；默认人群包名称填写“共同浏览｜SK-II × 资生堂｜化妆水/爽肤水”。',
    hint: '两个名称都准确填写后才能继续。',
  },
  {
    id: 'save-tutorial-draft',
    target: '[data-tutorial-target="save-solution-draft"]',
    phase: '第 3 章 · 保存并提交方案',
    eyebrow: '保存草稿',
    title: '先保存本次方案修改',
    body: '保存会把两个节点、三个自定义字段和方案名称一起写入草稿，形成可恢复的阶段成果。',
    hint: '点击顶部保存图标。',
  },
  {
    id: 'publish-tutorial-solution',
    target: '[data-tutorial-target="publish-solution"]',
    phase: '第 3 章 · 保存并提交方案',
    eyebrow: '提交正式方案',
    title: '点击「发布正式方案」',
    body: '发布前系统会再次核对节点和字段数量，不会跳过确认直接提交。',
    hint: '点击顶部发布图标。',
  },
  {
    id: 'confirm-publish-tutorial-solution',
    target: '.el-message-box__btns .el-button--primary',
    phase: '第 3 章 · 保存并提交方案',
    eyebrow: '提交正式方案',
    title: '确认发布这份方案',
    body: '确认内容应为 2 个组件、3 个自定义字段。发布成功后，它会出现在数据引擎人群圈包的“已发布方案”中。',
    hint: '点击“确认发布”。',
  },
  {
    id: 'open-workbench-after-publish',
    target: '[data-tutorial-target="open-workbench"] .el-radio-button__inner',
    focusPadding: 1,
    focusRadius: 999,
    phase: '第 3 章 · 保存并提交方案',
    eyebrow: '方案已形成',
    title: '返回「数据引擎人群圈包」试用方案',
    body: '制作完成不等于用户真的会用。最后一章会先按默认参数圈一次，再只改两个自定义字段圈第二次。',
    hint: '点击顶部“数据引擎人群圈包”。',
  },
  {
    id: 'open-solution-picker',
    target: '[data-tutorial-target="open-solution-picker"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '加载正式方案',
    title: '进入业务提效环节：复用一套圈人逻辑',
    body: '第四章是整套教程最重要的业务提效环节。第一次任务完成后，你不需要重新搭建方案，只要更换分析类目和竞争品牌，就能快速完成下一次竞品圈人。',
    hint: '点击高亮的“选方案”。',
  },
  {
    id: 'load-tutorial-solution',
    target: '[data-tutorial-target="load-tutorial-solution"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '加载正式方案',
    title: '选择刚刚发布的方案',
    body: '加载后，圈包画布会显示三个自定义字段和两个底层节点，默认参数仍是化妆水/爽肤水、SK-II 与资生堂。',
    hint: '点击“拉力分析｜共同浏览本品与竞品”。',
  },
  {
    id: 'run-first-solution-automation',
    target: '[data-tutorial-target="start-automation"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第一次应用',
    title: '按默认参数自动化圈人',
    body: '第一次直接使用方案默认值，验证这份正式方案能真实执行。点击后仍会先显示登录提醒。',
    hint: '点击“自动化圈人”。',
  },
  {
    id: 'confirm-first-solution-automation',
    target: null,
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第一次应用',
    title: '确认执行默认方案',
    body: '本次应圈选：近 30 天在天猫同时浏览 SK-II 与资生堂化妆水/爽肤水的人。',
    warning: {
      title: '请确保已登录数据引擎',
      body: '未登录会导致自动化圈人失败；教程只会在收到真实成功结果后记录第一次应用。',
    },
    hint: '确认登录状态后开始执行。',
  },
  {
    id: 'wait-first-solution-automation',
    target: '[data-tutorial-target="start-automation"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第一次应用',
    title: '等待第一次真实圈人结果',
    body: '成功后教程会记录当前方案 ID、类目、竞品和人群包名称；失败可以在这里重试，不会丢失前面的方案成果。',
    hint: '只有真实成功才进入参数修改。',
  },
  {
    id: 'open-analysis-field',
    target: '[data-tutorial-target="edit-analysis-field"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '业务提效功能',
    title: '换一个分析任务，不用重新搭建方案',
    body: '现在要把“SK-II 与资生堂的化妆水/爽肤水分析”快速复用为“SK-II 与 CPB 的面部护理套装分析”。整套浏览条件已经准备好，只需要更换分析类目和竞争品牌两个业务参数。',
    hint: '先点击“分析类目”；后续行为、渠道、时间和交集关系都可以直接复用。',
  },
  {
    id: 'change-analysis-category',
    target: '[data-tutorial-target="edit-analysis-value"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第二次应用',
    title: '改为「面部护理套装」',
    body: '选择“美容护肤/美体/精油>面部护理套装”。保存后，本品和竞品两个节点的类目会同时更新。',
    hint: '一个入口，同时影响 2 个组件。',
  },
  {
    id: 'save-analysis-category',
    target: '[data-tutorial-target="save-custom-field-value"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第二次应用',
    title: '保存分析类目修改',
    body: '点击保存，观察两个绑定节点同步变化；教程会检查两个节点是否都已改成面部护理套装。',
    hint: '点击“保存”。',
  },
  {
    id: 'open-competitor-field',
    target: '[data-tutorial-target="edit-competitor-field"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第二次应用',
    title: '打开「竞争品牌」',
    body: '接下来只替换竞品参数，本品牌 SK-II 保持不变。',
    hint: '点击“竞争品牌”卡片右侧的绑定数量。',
  },
  {
    id: 'change-competitor-brand',
    target: '[data-tutorial-target="edit-competitor-value"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第二次应用',
    title: '竞争品牌改为「CPB/肌肤之钥」',
    body: '选择 CPB/肌肤之钥。保存后只会更新竞品节点，本品牌节点仍是 SK-II。',
    hint: '选择 CPB/肌肤之钥。',
  },
  {
    id: 'save-competitor-brand',
    target: '[data-tutorial-target="save-custom-field-value"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第二次应用',
    title: '保存竞争品牌修改',
    body: '教程会同时校验：竞品变成 CPB、本品牌仍是 SK-II，节点数量仍然只有 2 个。',
    hint: '点击“保存”。',
  },
  {
    id: 'inspect-linked-update',
    target: '[data-tutorial-target="solution-use-area"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '看见提效结果',
    title: '只改 2 个参数，两个节点已经同步完成',
    body: '分析类目的一次修改同时作用于本品与竞品节点；竞争品牌的一次修改只作用于竞品节点。你没有新增节点，也没有重复配置行为、渠道和时间。',
    hint: '看懂联动结果后，为第二次圈人更新名称。',
  },
  {
    id: 'set-second-audience-name',
    target: '[data-tutorial-target="audience-name"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第二次应用',
    title: '更新第二次人群包名称',
    body: '填写“共同浏览｜SK-II × CPB｜面部护理套装”，让两次真实任务在数据引擎中可以清楚区分。',
    hint: '名称准确填写后继续。',
  },
  {
    id: 'run-second-solution-automation',
    target: '[data-tutorial-target="start-automation"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第二次应用',
    title: '再次点击「自动化圈人」',
    body: '这次执行的是同一正式方案，只修改了分析类目和竞争品牌两个参数。',
    hint: '点击“自动化圈人”。',
  },
  {
    id: 'confirm-second-solution-automation',
    target: null,
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第二次应用',
    title: '确认执行修改后的方案',
    body: '本次应圈选：近 30 天在天猫同时浏览 SK-II 与 CPB 面部护理套装的人。',
    warning: {
      title: '请确保已登录数据引擎',
      body: '教程会将这次真实成功与第一次结果对比，确认是同一方案、不同参数。',
    },
    hint: '确认后开始第二次圈人。',
  },
  {
    id: 'wait-second-solution-automation',
    target: '[data-tutorial-target="start-automation"]',
    phase: '第 4 章 · 两次应用验证提效',
    eyebrow: '第二次应用',
    title: '等待第二次真实圈人结果',
    body: '成功后系统会校验两次任务名称和参数均不同，并确认没有为第二次任务新增节点。',
    hint: '失败可重试；真实成功后才算完成教程。',
  },
  {
    id: 'solution-tutorial-complete',
    target: null,
    phase: '完成',
    eyebrow: '任务完成',
    title: '你已经做出并真实复用了一个方案',
    body: '你完成了从条件搭建、字段封装、方案发布到两次真实应用的完整闭环。这个方案也会保留在你的方案库里，下一篇可以继续把它扩展成拉力分析方案组。',
    hint: '成果已保留：1 个正式方案、3 个自定义字段、2 次成功圈人。',
  },
])

export const PULL_ANALYSIS_GROUP_TUTORIAL_STEPS = Object.freeze([
  {
    id: 'pull-open-picker-base',
    target: '[data-tutorial-target="open-solution-picker"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '复用已有成果',
    title: '从上次做好的共同浏览方案开始',
    body: '这次不重新搭建两个浏览节点，而是在已有方案上增加购买节点。先打开左侧已发布方案列表。',
    hint: '点击高亮的“选方案”。',
  },
  {
    id: 'pull-load-base-solution',
    target: '[data-tutorial-target="pull-load-base-solution"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '加载基础方案',
    title: '打开「共同浏览本品与竞品」',
    body: '教程会从这份正式方案继续制作，并保留其中的分析类目、本品牌和竞争品牌三个自定义字段。',
    hint: '选择上一个教程发布的方案。',
  },
  {
    id: 'pull-save-own-copy',
    target: '[data-tutorial-target="pull-save-as-solution"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '保留原方案',
    title: '另存为一个新方案',
    body: '另存为会保留原来的共同浏览方案，同时生成一份可以继续编辑的新草稿。',
    hint: '点击中间栏的“另存为新方案”图标。',
  },
  {
    id: 'pull-name-own-draft',
    target: null,
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '填写方案名称',
    title: '粘贴「共同浏览且购买本品」方案名称',
    body: '点击下方复制按钮，把名称粘贴到系统输入框，再点击保存。',
    hint: '教程会核对方案名称，避免后续拖错方案。',
  },
  {
    id: 'pull-open-center-own',
    target: '[data-tutorial-target="open-solution-center"] .el-radio-button__inner',
    focusPadding: 1,
    focusRadius: 999,
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '继续编辑草稿',
    title: '进入「数据引擎取数模板」',
    body: '新草稿已经保留了两个浏览节点和三个自定义字段，接下来增加购买本品节点。',
    hint: '点击顶部“数据引擎取数模板”。',
  },
  {
    id: 'pull-open-own-draft',
    target: '[data-tutorial-target="pull-own-draft"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '打开真实草稿',
    title: '打开刚刚另存的方案',
    body: '教程只高亮刚才生成的草稿，避免修改其他正式方案。',
    hint: '点击高亮草稿。',
  },
  {
    id: 'pull-duplicate-competitor-node',
    target: '[data-tutorial-target="pull-duplicate-node-1"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '增加第三个节点',
    title: '复制第二个「浏览竞品」节点',
    body: '复制第二个节点会把新节点追加到末尾，保持“浏览本品 ∩ 浏览竞品 ∩ 新节点”的正确顺序。',
    hint: '只能复制第二个节点。',
  },
  {
    id: 'pull-skip-auto-bind',
    target: null,
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '避免错误继承',
    title: '点击「跳过并继续」',
    body: '复制来源是竞品节点，但新节点要代表购买本品，所以本次不继承原来的竞争品牌绑定。',
    hint: '点击弹窗中唯一的“跳过并继续”。',
  },
  {
    id: 'pull-set-own-purchase',
    target: '[data-tutorial-target="solution-node-2-bhv"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '修改第三个节点',
    title: '行为由「浏览」改为「购买」',
    body: '取消浏览并选择购买，让第三个节点表达共同浏览人群中的本品购买者。',
    hint: '节点3只保留“购买”。',
  },
  {
    id: 'pull-set-own-brand',
    target: '[data-tutorial-target="solution-node-2-stdBrand"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '修改第三个节点',
    title: '标准品牌改为「SK-II」',
    body: '第三个节点代表购买本品，因此标准品牌应从资生堂改为本品牌 SK-II。',
    hint: '选择 SK-II。',
  },
  {
    id: 'pull-check-own-intersections',
    target: '[data-tutorial-target="pull-third-intersection"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '核对业务关系',
    title: '三个节点都使用「交集」',
    body: '最终逻辑应为：浏览本品 ∩ 浏览竞品 ∩ 购买本品。教程会同时检查两个连接关系。',
    hint: '确认节点2和节点3上方都选择了交集。',
  },
  {
    id: 'pull-edit-own-analysis',
    target: '[data-tutorial-target="pull-edit-analysis-field"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '扩展一对多字段',
    title: '编辑「分析类目」',
    body: '让一个分析类目参数同时控制三个节点，之后换类目只改一次。',
    hint: '点击“分析类目”右侧的编辑。',
  },
  {
    id: 'pull-bind-own-analysis',
    target: '[data-tutorial-target="solution-node-2-leafCates"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '扩展一对多字段',
    title: '绑定节点3的类目',
    body: '点击节点3类目字段的空白处，把第三条绑定加入“分析类目”。不要点击已经选中的类目标签。',
    hint: '绑定数量应从2变成3。',
  },
  {
    id: 'pull-save-own-analysis',
    target: '[data-tutorial-target="finish-custom-field"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '保存字段关系',
    title: '保存「分析类目」编辑',
    body: '保存后，一个分析类目参数会同时控制三个节点。',
    hint: '点击“保存编辑”。',
  },
  {
    id: 'pull-edit-own-brand-field',
    target: '[data-tutorial-target="pull-edit-own-brand-field"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '扩展本品牌字段',
    title: '编辑「本品牌」',
    body: '购买本品节点也应该跟随本品牌参数一起变化。',
    hint: '点击“本品牌”右侧的编辑。',
  },
  {
    id: 'pull-bind-own-brand',
    target: '[data-tutorial-target="solution-node-2-stdBrand"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '扩展本品牌字段',
    title: '绑定节点3的标准品牌',
    body: '点击字段空白处，将节点3的 SK-II 加入“本品牌”绑定。',
    hint: '本品牌的绑定数量应从1变成2。',
  },
  {
    id: 'pull-save-own-brand',
    target: '[data-tutorial-target="finish-custom-field"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '保存字段关系',
    title: '保存「本品牌」编辑',
    body: '至此，分析类目控制3个节点，本品牌控制节点1和节点3，竞争品牌仍只控制节点2。',
    hint: '点击“保存编辑”。',
  },
  {
    id: 'pull-set-own-identity',
    target: '[data-tutorial-target="solution-identity"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '补全方案信息',
    title: '核对方案名称和默认人群包名称',
    body: '两个名称都可以一键复制。方案名称便于组合管理，人群包名称会成为组合执行时的任务名称。',
    hint: '分别复制并粘贴两个名称。',
  },
  {
    id: 'pull-save-own-draft',
    target: '[data-tutorial-target="save-solution-draft"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '保存方案',
    title: '保存完整草稿',
    body: '系统会核对三个交集节点及分析类目、本品牌、竞争品牌的绑定关系。',
    hint: '点击顶部保存图标。',
  },
  {
    id: 'pull-publish-own',
    target: '[data-tutorial-target="publish-solution"]',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '发布正式方案',
    title: '提交「共同浏览且购买本品」',
    body: '发布后，这个方案才能加入方案文件夹并参与组合应用。',
    hint: '点击发布图标。',
  },
  {
    id: 'pull-confirm-publish-own',
    target: '.el-message-box__btns .el-button--primary',
    phase: '第 1 章 · 共同浏览且购买本品',
    eyebrow: '发布正式方案',
    title: '确认发布',
    body: '确认内容为3个组件、3个自定义字段。',
    hint: '点击“确认发布”。',
  },
  {
    id: 'pull-open-workbench-competitor',
    target: '[data-tutorial-target="open-workbench"] .el-radio-button__inner',
    focusPadding: 1,
    focusRadius: 999,
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '继续复用',
    title: '返回「数据引擎人群圈包」',
    body: '购买本品方案已经完成。下一份方案只需要调整节点3及两条品牌绑定。',
    hint: '点击顶部“数据引擎人群圈包”。',
  },
  {
    id: 'pull-load-own-solution',
    target: '[data-tutorial-target="pull-load-own-solution"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '加载上一份成果',
    title: '打开「共同浏览且购买本品」',
    body: '继续从刚发布的三节点方案另存，不再重复复制和配置类目。',
    hint: '点击高亮方案。',
  },
  {
    id: 'pull-save-competitor-copy',
    target: '[data-tutorial-target="pull-save-as-solution"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '创建第二份派生方案',
    title: '再次另存为新方案',
    body: '保留购买本品方案，另存一份购买竞品草稿。',
    hint: '点击“另存为新方案”。',
  },
  {
    id: 'pull-name-competitor-draft',
    target: null,
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '填写方案名称',
    title: '粘贴「共同浏览且购买竞品」方案名称',
    body: '一键复制名称，粘贴到系统输入框并保存。',
    hint: '名称准确后才能继续。',
  },
  {
    id: 'pull-open-center-competitor',
    target: '[data-tutorial-target="open-solution-center"] .el-radio-button__inner',
    focusPadding: 1,
    focusRadius: 999,
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '编辑第二份草稿',
    title: '进入「数据引擎取数模板」',
    body: '接下来先解除节点3与本品牌的关系，再把它改成竞争品牌。',
    hint: '点击顶部“数据引擎取数模板”。',
  },
  {
    id: 'pull-open-competitor-draft',
    target: '[data-tutorial-target="pull-competitor-draft"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '打开真实草稿',
    title: '打开刚刚另存的购买竞品草稿',
    body: '当前节点3仍然是购买本品，下面按安全顺序修改。',
    hint: '点击高亮草稿。',
  },
  {
    id: 'pull-edit-unbind-own',
    target: '[data-tutorial-target="pull-edit-own-brand-field"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '先解除联动',
    title: '先编辑「本品牌」',
    body: '如果不先解绑，直接修改节点3品牌可能同步影响节点1。',
    hint: '点击“本品牌”右侧的编辑。',
  },
  {
    id: 'pull-unbind-own-node',
    target: '[data-tutorial-target="solution-node-2-stdBrand"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '先解除联动',
    title: '再次点击节点3的标准品牌以解绑',
    body: '点击字段空白处，将节点3从“本品牌”中移除；节点1仍然保留绑定。',
    hint: '本品牌的绑定数量应从2回到1。',
  },
  {
    id: 'pull-save-own-unbind',
    target: '[data-tutorial-target="finish-custom-field"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '保存解绑结果',
    title: '保存「本品牌」编辑',
    body: '解绑保存后，再修改节点3不会影响节点1。',
    hint: '点击“保存编辑”。',
  },
  {
    id: 'pull-set-competitor-brand',
    target: '[data-tutorial-target="solution-node-2-stdBrand"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '修改购买对象',
    title: '节点3标准品牌改为「Shiseido/资生堂」',
    body: '行为仍是购买，只把购买对象由本品改为竞争品牌。',
    hint: '选择 Shiseido/资生堂。',
  },
  {
    id: 'pull-edit-competitor-field',
    target: '[data-tutorial-target="pull-edit-competitor-brand-field"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '绑定竞争品牌',
    title: '编辑「竞争品牌」',
    body: '让浏览竞品和购买竞品两个节点共享同一个竞争品牌参数。',
    hint: '点击“竞争品牌”右侧的编辑。',
  },
  {
    id: 'pull-bind-competitor-node',
    target: '[data-tutorial-target="solution-node-2-stdBrand"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '绑定竞争品牌',
    title: '绑定节点3的标准品牌',
    body: '点击字段空白处，将节点3加入“竞争品牌”。',
    hint: '竞争品牌的绑定数量应从1变成2。',
  },
  {
    id: 'pull-save-competitor-field',
    target: '[data-tutorial-target="finish-custom-field"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '保存字段关系',
    title: '保存「竞争品牌」编辑',
    body: '现在本品牌只控制节点1，竞争品牌同时控制节点2和节点3。',
    hint: '点击“保存编辑”。',
  },
  {
    id: 'pull-understand-name-rule',
    target: '[data-tutorial-target="custom-field-panel"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '组合方案关键规则',
    title: '公共字段名称必须保持一致',
    body: '组合应用按字段名称聚合。“竞争品牌”和“竞品品牌”会被视为两个参数；同名字段的类型也必须一致。',
    hint: '确认三个字段仍叫“分析类目、本品牌、竞争品牌”。',
  },
  {
    id: 'pull-set-competitor-identity',
    target: '[data-tutorial-target="solution-identity"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '补全方案信息',
    title: '设置购买竞品方案与人群包名称',
    body: '分别一键复制方案名称和默认人群包名称，再粘贴到对应输入框。',
    hint: '两个名称都准确填写。',
  },
  {
    id: 'pull-save-competitor-draft',
    target: '[data-tutorial-target="save-solution-draft"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '保存方案',
    title: '保存购买竞品草稿',
    body: '系统会检查三个节点和三项字段关系。',
    hint: '点击顶部保存图标。',
  },
  {
    id: 'pull-publish-competitor',
    target: '[data-tutorial-target="publish-solution"]',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '发布正式方案',
    title: '提交「共同浏览且购买竞品」',
    body: '发布完成后，组成拉力分析方案组所需的三个方案就全部齐了。',
    hint: '点击发布图标。',
  },
  {
    id: 'pull-confirm-publish-competitor',
    target: '.el-message-box__btns .el-button--primary',
    phase: '第 2 章 · 共同浏览且购买竞品',
    eyebrow: '发布正式方案',
    title: '确认发布',
    body: '确认内容为3个组件、3个自定义字段。',
    hint: '点击“确认发布”。',
  },
  {
    id: 'pull-create-folder',
    target: '[data-tutorial-target="pull-create-folder"]',
    phase: '第 3 章 · 组成拉力分析方案组',
    eyebrow: '收拢三份方案',
    title: '新建一个方案文件夹',
    body: '文件夹不仅用于整理，还可以把其中的多个已发布方案作为一个组合来应用。',
    hint: '点击方案文件夹旁的“新建”。',
  },
  {
    id: 'pull-name-folder',
    target: '[data-tutorial-target="pull-folder-name"]',
    phase: '第 3 章 · 组成拉力分析方案组',
    eyebrow: '命名方案组',
    title: '粘贴拉力分析文件夹名称',
    body: '一键复制“拉力分析｜本品与竞品浏览转化”，粘贴后点击确定。',
    hint: '系统会记录新文件夹 ID，避免拖入同名旧文件夹。',
  },
  {
    id: 'pull-move-three-solutions',
    target: '[data-tutorial-target="pull-folder-workspace"]',
    focusPadding: 0,
    phase: '第 3 章 · 组成拉力分析方案组',
    eyebrow: '拖入三份方案',
    title: '把三个已发布方案拖入新文件夹',
    body: '依次拖入共同浏览、购买本品和购买竞品。整个左侧区域都可以操作，教程会同时校验方案 ID 和文件夹 ID。',
    hint: '完成3/3后自动继续。',
  },
  {
    id: 'pull-open-workbench-group',
    target: '[data-tutorial-target="open-workbench"] .el-radio-button__inner',
    focusPadding: 1,
    focusRadius: 999,
    phase: '第 3 章 · 组成拉力分析方案组',
    eyebrow: '应用方案组合',
    title: '返回「数据引擎人群圈包」',
    body: '三个方案已经进入同一个文件夹，接下来体验一次组合应用。',
    hint: '点击顶部“数据引擎人群圈包”。',
  },
  {
    id: 'pull-open-picker-group',
    target: '[data-tutorial-target="open-solution-picker"]',
    phase: '第 3 章 · 组成拉力分析方案组',
    eyebrow: '打开方案列表',
    title: '再次打开「选方案」',
    body: '新文件夹会显示一个带数字3的组合应用入口。',
    hint: '点击“选方案”。',
  },
  {
    id: 'pull-open-group-preview',
    target: '[data-tutorial-target="pull-open-group"]',
    phase: '第 3 章 · 组成拉力分析方案组',
    eyebrow: '应用方案组合',
    title: '点击文件夹右侧的「✦ 3」',
    body: '数字3表示文件夹中有3个可组合应用的已发布方案。',
    hint: '点击组合应用徽标。',
  },
  {
    id: 'pull-enter-group',
    target: '.batch-composer-dialog',
    phase: '第 3 章 · 组成拉力分析方案组',
    eyebrow: '看懂参数聚合',
    title: '3个公共参数控制16处底层绑定',
    body: '分析类目覆盖8处，本品牌覆盖4处，竞争品牌覆盖4处。名称和类型一致的字段才会聚合。',
    hint: '核对3个人群包和3个公共参数后，进入组合圈包模式。',
  },
  {
    id: 'pull-inspect-group-packages',
    target: '[data-tutorial-target="pull-batch-package-1"]',
    focusPadding: 2,
    phase: '第 4 章 · 看懂组合方案并跑默认场景',
    eyebrow: '逐个检查三个方案',
    title: '切换查看三个人群包的具体参数',
    body: '顶部每个标签都对应一份已发布方案。切换后，中间画布会展示这份方案自己的节点、行为和参数。',
    hint: '当前页已经看过；继续点击依次高亮的另外两个人群包。',
  },
  {
    id: 'pull-explain-aggregation-origin',
    target: '[data-tutorial-target="pull-aggregate-parameters"]',
    focusPadding: 4,
    phase: '第 4 章 · 看懂组合方案并跑默认场景',
    eyebrow: '参数从哪里来',
    title: '三个方案的同名字段，被聚合成三个组合参数',
    body: '系统按“字段名称 + 字段类型”归并。分析类目、本品牌、竞争品牌虽然来自三份方案，但在组合工作台只需各显示一个入口。',
    hint: '先看清每个组合参数来自哪些方案、控制多少处绑定。',
  },
  {
    id: 'pull-explain-aggregation-impact',
    target: '[data-tutorial-target="pull-aggregate-parameters"]',
    focusPadding: 4,
    phase: '第 4 章 · 看懂组合方案并跑默认场景',
    eyebrow: '修改会影响什么',
    title: '改一个组合参数，所有同名绑定一起更新',
    body: '修改“分析类目”会同步三个方案的8处类目；修改“竞争品牌”会同步4处竞品品牌；“本品牌”不改就继续保持 SK-II。',
    hint: '接下来先不改参数，运行一轮默认场景作为对照。',
  },
  {
    id: 'pull-run-baseline',
    target: '[data-tutorial-target="pull-run-batch"]',
    phase: '第 4 章 · 看懂组合方案并跑默认场景',
    eyebrow: '第一轮 · 默认参数',
    title: '先用默认参数圈完三个人群包',
    body: '先保留化妆水/爽肤水、SK-II 和资生堂，建立一轮可以对照的真实结果。',
    hint: '点击“自动化圈人”。',
  },
  {
    id: 'pull-select-all-baseline',
    target: '[data-tutorial-target="pull-batch-all"]',
    phase: '第 4 章 · 看懂组合方案并跑默认场景',
    eyebrow: '第一轮 · 选择范围',
    title: '选择「圈完全部人群包」',
    body: '共同浏览、购买本品、购买竞品会按顺序执行；失败项可以单独重试。',
    hint: '选择包含3个包的执行范围。',
  },
  {
    id: 'pull-confirm-baseline',
    target: '[data-tutorial-target="pull-confirm-batch-run"]',
    phase: '第 4 章 · 看懂组合方案并跑默认场景',
    eyebrow: '第一轮 · 最终确认',
    title: '确认执行默认场景',
    body: '系统将依次提交三个默认人群包，这一轮完成后再体验少量改参的提效过程。',
    warning: {
      title: '请确保已登录数据引擎',
      body: '未登录会导致自动化圈人失败；失败后可以只重试失败任务。',
    },
    hint: '确认登录状态后开始第一轮执行。',
  },
  {
    id: 'pull-wait-baseline',
    target: null,
    nonBlocking: true,
    phase: '第 4 章 · 看懂组合方案并跑默认场景',
    eyebrow: '第一轮 · 等待真实结果',
    title: '默认场景的三个人群包正在依次执行',
    body: '等待期间页面不会被锁住。只有三个真实任务全部成功，教程才会进入改参环节。',
    hint: '失败时只重试失败任务；3/3成功后自动继续。',
  },
  {
    id: 'pull-baseline-complete',
    target: '[data-tutorial-target="pull-package-tabs"]',
    focusPadding: 3,
    phase: '第 4 章 · 看懂组合方案并跑默认场景',
    eyebrow: '第一轮完成',
    title: '默认参数已经生成三类真实人群',
    body: '现在以这轮结果为对照，只修改分析类目和竞争品牌，不重新搭建任何节点。',
    hint: '继续进入第二轮，亲手验证组合参数的业务提效。',
  },
  {
    id: 'pull-open-batch-analysis',
    target: '[data-tutorial-target="pull-edit-batch-analysis"]',
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '修改公共参数',
    title: '打开「分析类目」',
    body: '第一轮已经完成。现在只打开这一个组合参数，修改一次就会连接3个方案中的8处类目字段。',
    hint: '点击分析类目卡片右侧的绑定数量。',
  },
  {
    id: 'pull-change-batch-category',
    target: '[data-tutorial-target="pull-edit-batch-category"]',
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '修改公共参数',
    title: '类目改为「面部护理套装」',
    body: '只修改这个入口，保存后8个底层节点会一起更新。',
    hint: '选择美容护肤/美体/精油>面部护理套装。',
  },
  {
    id: 'pull-save-batch-category',
    target: '[data-tutorial-target="save-custom-field-value"]',
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '同步到三个方案',
    title: '保存分析类目修改',
    body: '系统会将新类目同步写入3个人群包对应的8个节点。',
    hint: '点击“保存”。',
  },
  {
    id: 'pull-open-batch-competitor',
    target: '[data-tutorial-target="pull-edit-batch-competitor"]',
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '修改公共参数',
    title: '打开「竞争品牌」',
    body: '本品牌 SK-II 保持不变，只更换竞争品牌。',
    hint: '点击竞争品牌卡片右侧的绑定数量。',
  },
  {
    id: 'pull-change-batch-competitor',
    target: '[data-tutorial-target="pull-edit-batch-competitor-value"]',
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '修改公共参数',
    title: '竞争品牌改为「CPB/肌肤之钥」',
    body: '保存后，三个方案中的4处竞争品牌绑定会一起更新。',
    hint: '选择 CPB/肌肤之钥。',
  },
  {
    id: 'pull-save-batch-competitor',
    target: '[data-tutorial-target="save-custom-field-value"]',
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '同步到三个方案',
    title: '保存竞争品牌修改',
    body: '本品牌仍是 SK-II，竞争品牌的4处绑定已同步变成 CPB。',
    hint: '点击“保存”。',
  },
  {
    id: 'pull-inspect-batch-sync',
    target: '[data-tutorial-target="solution-use-area"]',
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '看见业务提效',
    title: '只改2个参数，3个方案已经同步完成',
    body: '你没有重新搭建任何节点：分析类目更新8处、竞争品牌更新4处，本品牌保持不变。系统也已为第二轮生成三个不重复的人群包名称。',
    hint: '核对第二轮名称与同步结果，然后再次批量圈人。',
  },
  {
    id: 'pull-run-second',
    target: '[data-tutorial-target="pull-run-batch"]',
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '第二轮 · 批量自动化圈人',
    title: '用新参数再次发起三个人群包',
    body: '这次的三个任务会使用面部护理套装和 CPB，第一轮结果不会被覆盖。',
    hint: '点击“自动化圈人”。',
  },
  {
    id: 'pull-select-all-second',
    target: '[data-tutorial-target="pull-batch-all"]',
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '第二轮 · 选择范围',
    title: '选择「圈完全部人群包」',
    body: '再次选择全部，系统会把三个新场景任务按顺序提交。',
    hint: '选择包含3个包的执行范围。',
  },
  {
    id: 'pull-confirm-second',
    target: '[data-tutorial-target="pull-confirm-batch-run"]',
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '第二轮 · 最终确认',
    title: '确认执行修改后的场景',
    body: '系统将再次提交共同浏览、购买本品和购买竞品三个新名称的人群包。',
    warning: {
      title: '请确保已登录数据引擎',
      body: '未登录会导致自动化圈人失败；失败后可以只重试失败任务。',
    },
    hint: '确认登录状态后开始第二轮执行。',
  },
  {
    id: 'pull-wait-second',
    target: null,
    nonBlocking: true,
    phase: '第 5 章 · 少量改参再圈三包',
    eyebrow: '第二轮 · 等待真实结果',
    title: '修改后的三个人群包正在依次执行',
    body: '等待期间页面不会被锁住。教程会分别记录两轮结果，第二轮3/3成功后才会完成。',
    hint: '失败时只重试失败任务；3/3成功后自动完成。',
  },
  {
    id: 'pull-group-complete',
    target: null,
    phase: '完成',
    eyebrow: '任务完成',
    title: '你已经做出一套可复用的拉力分析方案组',
    body: '你先用默认参数完成3个包，又只修改2个组合参数完成3个新包；3个方案、8个行为节点和16处字段绑定都无需重新搭建。',
    hint: '成果已保留：2个新方案、1个方案组、两轮共6次成功圈人。',
  },
])

export const COMBINATION_BATCH_TUTORIAL_STEPS = Object.freeze([
  { id: 'combo-open-group', target: '[data-tutorial-target="pull-open-group"]', phase: '第 4 课 · 多竞品批量圈人', eyebrow: '复用已有方案组', title: '打开刚完成的拉力方案组', body: '不需要重新搭建方案。在“我的方案”中找到刚完成的拉力文件夹，点击右侧数字 3，预览文件夹里的三份方案。', hint: '数字 3 代表这个文件夹中有三份可组合应用的方案。' },
  { id: 'combo-confirm-group', target: '[data-tutorial-target="pull-enter-group-action"]', phase: '第 4 课 · 多竞品批量圈人', eyebrow: '确认并应用', title: '点击「进入组合圈包模式」', body: '确认预览中包含共同浏览、购买本品和购买竞品三份方案，再点击弹窗底部按钮应用这套方案组合。教程会检查三份方案都包含“竞争品牌”字段。', hint: '必须由你点击应用；成功进入后，同名自定义字段会自动聚合为一个组合参数。' },
  { id: 'combo-open-field', target: '[data-tutorial-target="combo-edit-competitor"]', phase: '第 4 课 · 多竞品批量圈人', eyebrow: '统一入口', title: '打开组合参数「竞争品牌」', body: '三份方案里名称相同的“竞争品牌”已经聚合成一个入口。点击卡片右上角的绑定数量，进入参数编辑。', hint: '接下来只改这一个入口，就能同时影响三份方案中对应的竞品条件。' },
  { id: 'combo-open-excel', target: '[data-tutorial-target="parameter-excel-batch"]', phase: '第 4 课 · 多竞品批量圈人', eyebrow: '批量展开', title: '选择「Excel 批量」', body: '单次编辑只会得到一组结果；Excel 批量可以把每一行竞品名称展开为一整组三方案任务。', hint: '点击 Excel 批量，准备一次生成 3 × 3 共 9 个人群包。' },
  { id: 'combo-paste', target: '[data-tutorial-target="parameter-batch-input"]', phase: '第 4 课 · 多竞品批量圈人', eyebrow: '一列名单', title: '粘贴三个竞品，准备三组任务', body: '点击复制整列，再粘贴到输入框。每行一个品牌，三行分别生成一组三个人群包。', hint: '展开每组核对方案名称；3 行 × 3 个方案 = 9 个任务。' },
  { id: 'combo-create', target: '[data-tutorial-target="parameter-create-tasks"]', phase: '第 4 课 · 多竞品批量圈人', eyebrow: '确认影响范围', title: '生成 9 个建包任务', body: '竞争品牌会按各方案自己的绑定关系更新竞品浏览和竞品购买条件。本品购买节点仍使用本品牌。确认预览后点击生成。', hint: '原方案仍可复用，这次只是展开新的执行任务。' },
  { id: 'combo-start-automation', target: '[data-tutorial-target="combo-start-automation"]', phase: '第 4 课 · 多竞品批量圈人', eyebrow: '统一执行', title: '点击「自动化圈人」', body: '九个人群包已经生成，不需要逐个提交。点击右侧“自动化圈人”，打开批量执行范围选择。', hint: '系统暂时不会执行，下一步还要选择圈人范围。' },
  { id: 'combo-select-all', target: '[data-tutorial-target="pull-batch-all"]', phase: '第 4 课 · 多竞品批量圈人', eyebrow: '选择执行范围', title: '选择「圈完全部人群包」', body: '本次要一次完成三个竞品对应的九个人群包，不要只运行当前正在查看的一个包。', hint: '选择“圈完全部人群包”，再进行最终确认。' },
  { id: 'combo-confirm-run', target: '[data-tutorial-target="pull-confirm-batch-run"]', phase: '第 4 课 · 多竞品批量圈人', eyebrow: '最终确认', title: '开始自动化圈选 9 个人群包', body: '确认队列中共有九个包。系统会按照页签顺序逐个提交，并分别保留成功和失败状态。', hint: '确认已登录数据引擎，再点击“开始自动化圈人”。' },
  { id: 'combo-wait', target: null, nonBlocking: true, phase: '第 4 课 · 多竞品批量圈人', eyebrow: '等待真实结果', title: '正在执行三组、九个人群包', body: '等待期间可以查看各包状态。失败时检查平台登录与错误提示，再点击仅重试失败任务。', hint: '平台执行时间另计；九个包全部成功后自动进入成果页。' },
  { id: 'combo-complete', target: null, phase: '第 4 课 · 多竞品批量圈人', eyebrow: '业务成果', title: '三行竞品，九个人群包已经准备好', body: '人工需要分别准备九个包；你复用三份方案，粘贴一次名单并统一发起。下次从同一个文件夹进入组合工作台，换成自己的竞品名单即可。', hint: '完成的是人群圈选，可用于后续分析；不代表已取得销售额或验证浏览与购买的先后顺序。' },
])

export const PARAMETER_BATCH_TUTORIAL_STEPS = Object.freeze([
  {
    id: 'solution-clean-workbench',
    target: '[data-tutorial-target="clean-workbench"]',
    phase: '第 1 章 · 制作竞品购买方案',
    eyebrow: '开始前准备',
    title: '从一张干净圈包画布开始',
    body: '本次要先做出一份可复用的“竞品购买人群”方案，再只修改竞争品牌这一个参数，用 Excel 一列品牌批量展开成 4 个人群包。',
    hint: '确认画布已清空，开始制作方案。',
  },
  {
    id: 'add-public-behavior',
    target: '[data-tutorial-target="add-category-public"]',
    focusPadding: 0,
    phase: '第 1 章 · 制作竞品购买方案',
    eyebrow: '添加组件',
    title: '添加「类目公域行为」',
    body: '这个组件可以同时限定购买行为、分析类目、竞争品牌、渠道和时间，是批量竞品圈人的底稿。',
    hint: '只点击高亮的“添加 类目公域行为”。',
  },
  {
    id: 'parameter-set-purchase',
    target: '[data-tutorial-target="parameter-node-bhv"]',
    phase: '第 1 章 · 制作竞品购买方案',
    eyebrow: '配置节点',
    title: '行为选择「购买」',
    body: '这份方案要回答“近 30 天购买过某个竞争品牌的人是谁”，因此节点只保留购买行为。',
    hint: '选择“购买”。',
  },
  {
    id: 'parameter-set-category',
    target: '[data-tutorial-target="parameter-node-leafCates"]',
    phase: '第 1 章 · 制作竞品购买方案',
    eyebrow: '配置节点',
    title: '类目选择「化妆水/爽肤水」',
    body: '搜索并选择“美容护肤/美体/精油>化妆水/爽肤水”，把四个竞品放在同一类目口径下比较。',
    hint: '选中教程指定的底层类目。',
  },
  {
    id: 'parameter-set-brand',
    target: '[data-tutorial-target="parameter-node-stdBrand"]',
    phase: '第 1 章 · 制作竞品购买方案',
    eyebrow: '配置节点',
    title: '初始品牌选择「CPB/肌肤之钥」',
    body: '先用 CPB 作为方案默认值。发布后会把这个品牌参数开放，再用 Excel 一次替换成四个竞品。',
    hint: '选择 CPB/肌肤之钥。',
  },
  {
    id: 'parameter-set-channel',
    target: '[data-tutorial-target="parameter-node-channel"]',
    phase: '第 1 章 · 制作竞品购买方案',
    eyebrow: '配置节点',
    title: '渠道选择「天猫」',
    body: '统一限定在天猫渠道，保证后面四个人群包的业务口径完全一致。',
    hint: '选择天猫。',
  },
  {
    id: 'parameter-confirm-time',
    target: '[data-tutorial-target="parameter-node-time"]',
    phase: '第 1 章 · 制作竞品购买方案',
    eyebrow: '配置节点',
    title: '确认时间为过去 30 天',
    body: '保持默认的“过去 N 天”，数值为 30。这个公共条件会复制到之后生成的每一个人群包。',
    hint: '确认过去 30 天后继续。',
  },
  {
    id: 'save-workbench-solution',
    target: '[data-tutorial-target="save-workbench-solution"]',
    phase: '第 1 章 · 制作竞品购买方案',
    eyebrow: '形成草稿',
    title: '把当前圈包画布存为方案草稿',
    body: '保存后再到数据引擎取数模板中，把节点里的品牌封装成业务人员可以直接批量输入的自定义字段。',
    hint: '点击“存草稿”。',
  },
  {
    id: 'open-solution-center',
    target: '[data-tutorial-target="open-solution-center"] .el-radio-button__inner',
    focusPadding: 1,
    focusRadius: 999,
    phase: '第 2 章 · 开放竞争品牌参数',
    eyebrow: '进入模板制作',
    title: '打开「数据引擎取数模板」',
    body: '接下来不是重新搭方案，而是把刚才的底层品牌字段包装成“竞争品牌”参数。',
    hint: '点击顶部“数据引擎取数模板”。',
  },
  {
    id: 'open-workbench-draft',
    target: '[data-tutorial-target="tutorial-workbench-draft"]',
    phase: '第 2 章 · 开放竞争品牌参数',
    eyebrow: '选择真实草稿',
    title: '打开刚刚保存的「圈包草稿」',
    body: '系统会先查找刚刚生成的草稿；若列表同步稍慢，会自动刷新并保持页面可操作。',
    hint: '点击高亮草稿。',
  },
  {
    id: 'parameter-add-brand-field',
    target: '[data-tutorial-target="add-custom-field"]',
    phase: '第 2 章 · 开放竞争品牌参数',
    eyebrow: '创建业务入口',
    title: '新增「竞争品牌」自定义字段',
    body: '自定义字段会成为方案使用时的参数入口。用户以后不必进入节点寻找标准品牌字段。',
    hint: '点击“新增自定义字段”。',
  },
  {
    id: 'parameter-name-brand-field',
    target: '[data-tutorial-target="custom-field-name"]',
    phase: '第 2 章 · 开放竞争品牌参数',
    eyebrow: '命名业务入口',
    title: '字段名称输入「竞争品牌」',
    body: '这个名称会直接出现在方案应用区。输入后继续绑定节点中的标准品牌字段。',
    hint: '必须准确输入“竞争品牌”。',
  },
  {
    id: 'parameter-bind-brand-field',
    target: '[data-tutorial-target="solution-node-0-stdBrand"]',
    phase: '第 2 章 · 开放竞争品牌参数',
    eyebrow: '绑定底层字段',
    title: '点击节点的「标准品牌」空白处',
    body: '这条绑定把“竞争品牌”入口连接到当前 CPB 品牌字段。请点击已选品牌旁边的字段空白处。',
    hint: '不要点击 CPB 标签；点击字段空白处完成绑定。',
    warning: {
      title: '请点击字段空白处',
      body: '点击已选择的品牌会重新打开下拉框；点击同一字段内的空白位置才能建立绑定。',
    },
  },
  {
    id: 'parameter-finish-brand-field',
    target: '[data-tutorial-target="finish-custom-field"]',
    phase: '第 2 章 · 开放竞争品牌参数',
    eyebrow: '保存业务入口',
    title: '完成创建「竞争品牌」',
    body: '教程会校验它只绑定当前节点的标准品牌字段，避免 Excel 批量时写入错误参数。',
    hint: '确认 1 个绑定后点击“完成创建”。',
  },
  {
    id: 'parameter-set-identity',
    target: '[data-tutorial-target="solution-identity"]',
    phase: '第 3 章 · 发布可复用方案',
    eyebrow: '补全方案信息',
    title: '设置方案名称和默认人群包名称',
    body: '使用教程提供的两个名称，之后在工作台里可以准确找到这份正式方案。',
    hint: '名称可在引导卡中一键复制。',
  },
  {
    id: 'parameter-save-draft',
    target: '[data-tutorial-target="save-solution-draft"]',
    phase: '第 3 章 · 发布可复用方案',
    eyebrow: '保存阶段成果',
    title: '保存方案草稿',
    body: '把购买节点、竞争品牌字段和两个名称一起保存下来。',
    hint: '点击顶部保存图标。',
  },
  {
    id: 'parameter-publish-solution',
    target: '[data-tutorial-target="publish-solution"]',
    phase: '第 3 章 · 发布可复用方案',
    eyebrow: '形成正式方案',
    title: '发布这份竞品购买方案',
    body: '只有正式发布后，工作台才能加载方案并使用 Excel 批量参数。',
    hint: '点击顶部发布图标。',
  },
  {
    id: 'parameter-confirm-publish',
    target: '.el-message-box__btns .el-button--primary',
    phase: '第 3 章 · 发布可复用方案',
    eyebrow: '确认发布',
    title: '确认发布 1 个组件、1 个自定义字段',
    body: '确认无误后发布。接下来继续应用刚发布的这份方案，体验只改一个参数就能批量圈包。',
    hint: '点击“确认发布”。',
  },
  {
    id: 'parameter-open-workbench',
    target: '[data-tutorial-target="open-workbench"] .el-radio-button__inner',
    focusPadding: 1,
    focusRadius: 999,
    phase: '第 4 章 · Excel 批量生成四包',
    eyebrow: '开始应用方案',
    title: '返回「数据引擎人群圈包」',
    body: '方案已经沉淀好。现在体验核心提效：不再复制四次节点，只输入一列竞争品牌。',
    hint: '点击顶部“数据引擎人群圈包”。',
  },
  {
    id: 'open-solution-picker',
    target: '[data-tutorial-target="open-solution-picker"]',
    phase: '第 4 章 · Excel 批量生成四包',
    eyebrow: '应用正式方案',
    title: '打开已发布方案列表',
    body: '从“我的方案”中加载刚刚发布的竞品购买方案。',
    hint: '点击高亮的“选方案”。',
  },
  {
    id: 'load-tutorial-solution',
    target: '[data-tutorial-target="load-tutorial-solution"]',
    phase: '第 4 章 · Excel 批量生成四包',
    eyebrow: '应用正式方案',
    title: '选择刚刚发布的竞品购买方案',
    body: '加载后会看到一个“竞争品牌”参数，默认值仍是 CPB/肌肤之钥。',
    hint: '点击高亮方案。',
  },
  {
    id: 'parameter-open-brand-editor',
    target: '[data-tutorial-target="parameter-edit-brand"]',
    phase: '第 4 章 · Excel 批量生成四包',
    eyebrow: '进入参数编辑',
    title: '点击「竞争品牌」右上角的绑定数量',
    body: '这里既能单次修改品牌，也能进入 Excel 批量模式。',
    hint: '点击字段卡片右上角的数字。',
  },
  {
    id: 'parameter-open-excel',
    target: '[data-tutorial-target="parameter-excel-batch"]',
    phase: '第 4 章 · Excel 批量生成四包',
    eyebrow: '打开批量模式',
    title: '点击「Excel 批量」',
    body: '普通编辑只会改一个包；Excel 批量会把每一行参数独立生成一个建包任务。',
    hint: '点击右上角“Excel 批量”。',
  },
  {
    id: 'parameter-paste-brands',
    target: '[data-tutorial-target="parameter-batch-input"]',
    phase: '第 4 章 · Excel 批量生成四包',
    eyebrow: '粘贴一列竞争品牌',
    title: '复制并粘贴 4 个竞争品牌',
    body: '每行一个品牌，代表一个独立人群包。本次必须完整使用 CPB、兰蔻、雅诗兰黛和赫莲娜四行示例。',
    hint: '先点击“复制整列”，再粘贴到高亮输入框。',
  },
  {
    id: 'parameter-create-tasks',
    target: '[data-tutorial-target="parameter-create-tasks"]',
    phase: '第 4 章 · Excel 批量生成四包',
    eyebrow: '生成任务',
    title: '点击「生成 4 个建包任务」',
    body: '系统会校验行数、品牌名称和重复项；四行都正确后，才会生成四个独立人群包。',
    hint: '确认预览为 4 行、0 个需处理，再生成任务。',
  },
  {
    id: 'parameter-inspect-tasks',
    target: '[data-tutorial-target="pull-package-tabs"]',
    phase: '第 5 章 · 圈完全部人群包',
    eyebrow: '核对生成结果',
    title: '四个品牌已经展开成四个人群包',
    body: '每个页签保存一行独立品牌，一行一个品牌、一个品牌一个包；类目、购买行为、天猫和近 30 天保持一致。这就是“只改一个参数，批量生成多个包”。',
    hint: '确认上方出现 4 个人群包后继续。',
  },
  {
    id: 'parameter-start-automation',
    target: '[data-tutorial-target="parameter-start-automation"]',
    phase: '第 5 章 · 圈完全部人群包',
    eyebrow: '开始批量圈人',
    title: '点击「自动化圈人」',
    body: '系统会先让你选择执行范围，不会直接提交。',
    hint: '点击右侧“自动化圈人”。',
  },
  {
    id: 'parameter-select-all',
    target: '[data-tutorial-target="pull-batch-all"]',
    phase: '第 5 章 · 圈完全部人群包',
    eyebrow: '选择执行范围',
    title: '选择「圈完全部人群包」',
    body: '本次目标是一次依次圈完 4 个品牌包，不要只运行当前正在查看的一个包。',
    hint: '选择“圈完全部人群包”。',
  },
  {
    id: 'parameter-confirm-run',
    target: '[data-tutorial-target="pull-confirm-batch-run"]',
    phase: '第 5 章 · 圈完全部人群包',
    eyebrow: '最终确认',
    title: '开始自动化圈选 4 个人群包',
    body: '四个任务会按照页签顺序逐个提交，成功和失败状态会分别保留。',
    warning: {
      title: '请确保已登录数据引擎',
      body: '未登录会导致自动化圈人失败；失败后可以只重试失败任务。',
    },
    hint: '确认数据引擎已登录，再点击“开始自动化圈人”。',
  },
  {
    id: 'parameter-wait-automation',
    target: null,
    nonBlocking: true,
    phase: '第 5 章 · 圈完全部人群包',
    eyebrow: '等待真实执行结果',
    title: '正在依次圈选四个竞争品牌人群包',
    body: '等待期间页面不会被锁住。教程只会在 4/4 真实成功后打卡；如果有失败项，只需重试失败任务。',
    hint: '4/4 成功后自动进入完成页。',
  },
  {
    id: 'parameter-batch-complete',
    target: null,
    phase: '完成',
    eyebrow: '正式教程完成',
    title: '你已经用一个参数批量创建并圈完 4 个人群包',
    body: '以后分析多个竞品品牌的销售数据时，只需打开“竞争品牌”参数，把新品牌名单整列粘贴进来；系统会继续按一行一个品牌、一个品牌一个包批量创建。',
    hint: '成果已保留：1 个正式方案、1 个可批量字段、4 个成功人群包。',
  },
])

export const GUIDED_TUTORIAL_STEPS = Object.freeze({
  [CATEGORY_ITEM_TUTORIAL_ID]: CATEGORY_ITEM_TUTORIAL_STEPS,
  [DMP_BATCH_TUTORIAL_ID]: DMP_BATCH_TUTORIAL_STEPS,
  [SOLUTION_REUSE_TUTORIAL_ID]: SOLUTION_REUSE_TUTORIAL_STEPS,
  [PULL_ANALYSIS_GROUP_TUTORIAL_ID]: PULL_ANALYSIS_GROUP_TUTORIAL_STEPS,
  [PARAMETER_BATCH_TUTORIAL_ID]: PARAMETER_BATCH_TUTORIAL_STEPS,
  [COMBINATION_BATCH_TUTORIAL_ID]: COMBINATION_BATCH_TUTORIAL_STEPS,
})
