export const CATEGORY_ITEM_TUTORIAL_ID = 'category-item-behavior-split'

export const CATEGORY_ITEM_TUTORIAL_PRODUCT_IDS = Object.freeze([
  '566446518116',
  '620909794925',
  '537574170700',
  '540211731451',
  '634025846178',
  '577875075059',
  '1055622646901',
])

export const CATEGORY_ITEM_TUTORIAL_STEPS = Object.freeze([
  {
    id: 'clean-workbench',
    target: '[data-tutorial-target="clean-workbench"]',
    eyebrow: '开始前准备',
    title: '工作台已经为你自动清空',
    body: '教程会自动移除原有节点和参数，从一张干净画布开始。当前高亮的整个中间栏，就是接下来实际搭建人群条件的区域。',
    hint: '确认画布已经为空，然后开始搭建。',
  },
  {
    id: 'add-category-item',
    target: '[data-tutorial-target="add-category-item"]',
    eyebrow: '搭建组件',
    title: '添加「类目商品行为」',
    body: '在左侧行为组件库中点击“添加 类目商品行为”。它适合用商品 ID 圈选某一类具体商品行为。',
    hint: '现在只需要添加这一个组件。',
  },
  {
    id: 'select-behavior',
    target: '[data-tutorial-target="select-behavior"]',
    eyebrow: '设置通用参数',
    title: '任选一个业务行为',
    body: '加购、收藏、浏览、评论、购买或预售都可以选择。本教程推荐“购买”，但你可以根据自己的业务目标任选；所选行为会复制到后续拆出的每个节点。',
    hint: '推荐选择“购买”；选择任意一个行为即可继续。',
  },
  {
    id: 'set-time',
    target: '[data-tutorial-target="set-time"]',
    eyebrow: '设置通用参数',
    title: '选择适合业务的时间范围',
    body: '“过去 N 天”或“固定日期”都可以。本教程推荐近 30 天；拆分时系统会把你选择的时间自动复制到 7 个节点，无需逐个重复填写。',
    hint: '推荐“过去 30 天”；确认任意有效时间后即可继续。',
  },
  {
    id: 'copy-ids',
    target: null,
    eyebrow: '准备批量数据',
    title: '一次复制 7 个商品 ID',
    body: '真实工作中可以直接从 Excel 复制一整列。这里先用教程提供的 7 个 ID，点击下方按钮一次复制。',
    hint: '系统支持换行、逗号和 Tab 分隔。',
  },
  {
    id: 'paste-ids',
    target: '[data-tutorial-target="paste-product-ids"]',
    eyebrow: '批量输入',
    title: '粘贴到「商品 ID」',
    body: '实际工作中，你可以直接从 Excel 复制一整列商品 ID 粘贴过来。为了先熟悉流程，本次教程以示例中的 7 个商品 ID 为主；系统会先解析内容并展示匹配结果，不会立即拆分。',
    hint: '优先粘贴示例中的 7 个商品 ID；自己的 Excel 一列也可以直接替换。',
  },
  {
    id: 'add-product-ids',
    target: '[data-tutorial-target="add-product-ids"]',
    focusPadding: 0,
    focusRadius: 7,
    eyebrow: '检查解析结果',
    title: '确认添加 7 项',
    body: '确认解析结果为 7 项后，点击“添加 7 项”。因为单个类目商品行为组件只能放 1 个商品 ID，系统接下来会询问是否自动拆分。',
    hint: '这一刻仍然可以取消，不会直接改变节点结构。',
  },
  {
    id: 'confirm-split',
    target: '.el-message-box__btns .el-button--primary',
    eyebrow: '自动拆分',
    title: '确认拆分为 7 个并集节点',
    body: '系统已经识别到商品 ID 超限。点击“确认拆分”，7 个 ID 会各自进入一个节点，之前填写的行为和时间会被完整复制。',
    hint: '节点之间使用“并”，表示命中任意一个商品即可。',
  },
  {
    id: 'inspect-split',
    target: '[data-tutorial-target="split-result"]',
    eyebrow: '核对结果',
    title: '检查系统生成的 7 个节点',
    body: '滚动查看画布：每个节点应有 1 个商品 ID，并保留你刚才选择的行为和时间；第 2—7 个节点与前一个节点的关系应为“并”。',
    hint: '看懂结果后，点击“结果正确”。',
  },
  {
    id: 'name-audience',
    target: '[data-tutorial-target="audience-name"]',
    eyebrow: '完成建包信息',
    title: '填写人群包名称',
    body: '给本次圈选结果起一个便于业务识别的名称，例如“近30天购买指定7商品人群”。',
    hint: '名称填写完整后，再点击“名称已填好”。',
  },
  {
    id: 'start-automation',
    target: '[data-tutorial-target="start-automation"]',
    eyebrow: '准备执行',
    title: '点击「自动化圈人」',
    body: '到这里，节点、参数和人群包名称都已准备完成。点击“自动化圈人”进入最终确认；系统不会在这一步直接执行。',
    hint: '最终执行权仍然交给用户。',
  },
  {
    id: 'final-confirm',
    target: null,
    eyebrow: '最终确认',
    title: '确认后开始自动化圈人',
    body: '请最后核对：7 个类目商品行为节点、你选择的行为和时间、节点关系为并。确认无误后再执行。',
    hint: '执行后，教程会等待真实成功结果。',
  },
  {
    id: 'automation-running',
    target: '[data-tutorial-target="start-automation"]',
    eyebrow: '正在执行',
    title: '正在等待自动化结果',
    body: '系统正在把本次圈选任务交给数据引擎。请保持当前页面打开，成功后教程会自动进入完成页。',
    hint: '如果执行失败，可检查自动化插件后在这里重试。',
  },
  {
    id: 'tutorial-complete',
    target: null,
    eyebrow: '任务完成',
    title: '你已经独立完成了一次批量圈人',
    body: '这次你完成了：配置公共参数、批量粘贴 7 个商品 ID、自动拆成并集节点并发起圈人。下次可以把同样的方法用于自己的业务数据。',
    hint: '重点拓展：关键词、类目、品牌等限量字段，也能使用同样的批量拆分方法。',
  },
])
